notebooks

diff --git a/Install Jupyter Notebook.app/Contents/Resources/script b/Install Jupyter Notebook.app/Contents/Resources/script
--- a/Install Jupyter Notebook.app/Contents/Resources/script
+++ b/Install Jupyter Notebook.app/Contents/Resources/script
@@ -3,6 +3,7 @@
 # This file is used to install Jupyter Notebook
 # To use, type:
 # ./install.sh
+
 potential=($(ls -1 /Library/Frameworks/Python.framework/Versions/3.[6,7,8,9]/bin/python3 2> /dev/null))
 if [ ! $? == 0 ]; then
 	echo "-----"; echo "You need to download:"; echo; echo "PYTHON 3 (3.6.0 or greater)"; echo; echo "from http://python.org/downloads/"; echo; echo "to continue"; echo; open "http://python.org/downloads/"; exit 1;
@@ -21,5 +22,16 @@ echo
 
 pipcommand=`echo $potential | sed -e 's/python3$/pip3/'`
 $pipcommand install -r ../../../requirements.txt
+pipresult=$?
 
-echo 👍
+if [ $pipresult == 0 ]; then
+    source ~/.bash_profile
+    echo "Changing notebook theme for all notebooks"
+    jt -t grade3  # change theme
+    echo 👍
+    exit 0
+fi
+
+echo "An error occurred and was unable to install"
+echo "Error #: "$pipresult
+echo 👎
